# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d538caa5edaefc3f40b7325fcd575cb7c1a1bc08b8d6670486399ce44c0259f6cfaeeb914660cf46f80654a8947a48ea26f0b3ac6553948defb32ea8a0faeeec

test:
  secret_key_base: 54d56cf279fe8d180c540c400ac19292eb8d9ab10994f2f0ae50bc0aa00ef17b8e47a3ac5d46a98cd2577cd354eba172e78e6de9570ba0b70bc7126d1acbf3d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
